version: '3.8'

services:
    web:
        container_name: fastapi_app
        build: .
        command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
          - .:/app
        ports:
          - 8000:8000
        depends_on:
          - db
        restart: always


    db:
      container_name: postgresql_db
      image: postgres:13-alpine
      restart: always
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=test_user
        - POSTGRES_PASSWORD=test_password
        - POSTGRES_DB=test_db



    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4:4.18
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: email@email.com
        PGADMIN_DEFAULT_PASSWORD: test_password
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      depends_on:
        - db
