"""cascade

Revision ID: 698db08ad003
Revises: 48186fa153e6
Create Date: 2021-10-29 10:55:42.179148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698db08ad003'
down_revision = '48186fa153e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
