"""cascade1

Revision ID: 7081101dbd06
Revises: 698db08ad003
Create Date: 2021-10-29 10:58:44.749483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7081101dbd06'
down_revision = '698db08ad003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
