"""Role permission table change

Revision ID: d21ed47c66d8
Revises: 44e76f2bb809
Create Date: 2021-10-28 11:38:35.277618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21ed47c66d8'
down_revision = '44e76f2bb809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
