"""cascade 4

Revision ID: d5572c096b55
Revises: ef185ea34a64
Create Date: 2021-10-29 11:09:04.875789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5572c096b55'
down_revision = 'ef185ea34a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_permission_role_id_fkey', 'role_permission', type_='foreignkey')
    op.drop_constraint('role_permission_permission_id_fkey', 'role_permission', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'roles', ['role_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'role_permission', 'permissions', ['permission_id'], ['id'], ondelete='cascade')
    op.drop_constraint('user_role_user_id_fkey', 'user_role', type_='foreignkey')
    op.drop_constraint('user_role_role_id_fkey', 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'user_role', 'roles', ['role_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key('user_role_role_id_fkey', 'user_role', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_role_user_id_fkey', 'user_role', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', type_='foreignkey')
    op.create_foreign_key('role_permission_permission_id_fkey', 'role_permission', 'permissions', ['permission_id'], ['id'])
    op.create_foreign_key('role_permission_role_id_fkey', 'role_permission', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
