"""cascade 3

Revision ID: ef185ea34a64
Revises: 7081101dbd06
Create Date: 2021-10-29 11:02:57.327763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef185ea34a64'
down_revision = '7081101dbd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
